parameters:
  androidPool: { }
  iosPool: { }
  windowsPool: { }
  macosPool: { }
  androidApiLevels: [ 30 ]
  iosVersions: [ 'latest' ]
  provisionatorChannel: 'latest'
  agentPoolAccessToken: ''
  projects:
    - name: name
      desc: Human Description
      android: /optional/path/to/android.csproj
      ios: /optional/path/to/ios.csproj
      winui: /optional/path/to/winui.csproj
      mac: /optional/path/to/mac.csproj
      app: /optional/path/to/app.csproj

stages:

  - stage: android_ui_tests
    displayName: Android UITests
    dependsOn: []
    jobs:
      - ${{ each project in parameters.projects }}:
        - ${{ if ne(project.android, '') }}:
          - ${{ each api in parameters.androidApiLevels }}:
            - ${{ if not(containsValue(project.androidApiLevelsExclude, api)) }}:
              - job: android_ui_tests_${{ project.name }}_${{ api }}
                timeoutInMinutes: 120 # how long to run the job before automatically cancelling
                workspace:
                  clean: all
                displayName: ${{ coalesce(project.desc, project.name) }} (API ${{ api }})
                pool: ${{ parameters.androidPool }}
                variables:
                  ${{ if ge(api, 24) }}:
                    ANDROID_EMULATORS: "system-images;android-${{ api }};google_apis_playstore;x86"
                  ${{ if lt(api, 24) }}:
                    ANDROID_EMULATORS: "system-images;android-${{ api }};google_apis;x86"
                  REQUIRED_XCODE: $(DEVICETESTS_REQUIRED_XCODE)
                steps:
                  - template: ui-tests-steps.yml
                    parameters:
                      platform: android
                      version: ${{ api }}
                      path: ${{ project.android }}
                      app: ${{ project.app }}
                      device: android-emulator-32_${{ api }}
                      provisionatorChannel: ${{ parameters.provisionatorChannel }}
                      agentPoolAccessToken: ${{ parameters.agentPoolAccessToken }}

  - stage: ios_ui_tests
    displayName: iOS UITests
    dependsOn: []
    jobs:
      - ${{ each project in parameters.projects }}:
        - ${{ if ne(project.ios, '') }}:
          - ${{ each version in parameters.iosVersions }}:
            - ${{ if not(containsValue(project.iosVersionsExclude, version)) }}:
              - job: ios_ui_tests_${{ project.name }}_${{ replace(version, '.', '_') }}
                workspace:
                  clean: all
                displayName: ${{ coalesce(project.desc, project.name) }} (v${{ version }})
                pool: ${{ parameters.iosPool }}
                variables:
                  REQUIRED_XCODE: $(DEVICETESTS_REQUIRED_XCODE)
                steps:
                  - template: ui-tests-steps.yml
                    parameters:
                      platform: ios
                      ${{ if eq(version, 'latest') }}:
                        version: 16.2
                      ${{ if ne(version, 'latest') }}:
                        version: ${{ version }}
                      path: ${{ project.ios }}
                      app: ${{ project.app }}
                      ${{ if eq(version, 'latest') }}:
                        device: ios-simulator-64
                      ${{ if ne(version, 'latest') }}:
                        device: ios-simulator-64_${{ version }}
                      provisionatorChannel: ${{ parameters.provisionatorChannel }}
                      agentPoolAccessToken: ${{ parameters.agentPoolAccessToken }}

  - stage: winui_ui_tests
    displayName: WinUI UITests
    dependsOn: []
    jobs:
      - ${{ each project in parameters.projects }}:
        - ${{ if ne(project.winui, '') }}:
              - job: winui_ui_tests_${{ project.name }}
                workspace:
                  clean: all
                displayName: ${{ coalesce(project.desc, project.name) }}
                pool: ${{ parameters.windowsPool }}
                steps:
                  - template: ui-tests-steps.yml
                    parameters:
                      platform: windows
                      version: "10.0.19041"
                      device: windows10
                      path: ${{ project.winui }}
                      app: ${{ project.app }}
                      provisionatorChannel: ${{ parameters.provisionatorChannel }}
                      agentPoolAccessToken: ${{ parameters.agentPoolAccessToken }}

  - stage: mac_ui_tests
    displayName: macOS UITests
    dependsOn: []
    jobs:
      - ${{ each project in parameters.projects }}:
        - ${{ if ne(project.mac, '') }}:
              - job: mac_ui_tests_${{ project.name }}
                workspace:
                  clean: all
                displayName: ${{ coalesce(project.desc, project.name) }}
                pool: ${{ parameters.macosPool }}
                steps:
                  - template: ui-tests-steps.yml
                    parameters:
                      platform: catalyst
                      version: "13.1"
                      device: mac
                      path: ${{ project.mac }}
                      app: ${{ project.app }}
                      provisionatorChannel: ${{ parameters.provisionatorChannel }}
                      agentPoolAccessToken: ${{ parameters.agentPoolAccessToken }}